### ISSUE TITLE
Running in http mode

### ISSUE THREAD

**Issue by kevdogg** [t4skforce/syncthing-discovery#2]
Hey I really enjoy your github and instructions.  Nice since a lot of documentation seems to be missing from the syncthing-discovery project in general.

My intentions are actually to try to run the discovery server behind a reverse proxy.  Your docker file has:

```
CMD ${USER_HOME}/server/discosrv \
    -listen=":${SERV_PORT}" \
    -db-dir="${USER_HOME}/db/discosrv.db" \
    -cert="${USER_HOME}/certs/cert.pem" \
    -key="${USER_HOME}/certs/key.pem" \
    ${DISCO_OPTS}
```

Just checking that if I made the following modifications to the Dockerfile, then the server would start listening via http:

```
ENV DISCO_OPTS      "-http"
CMD ${USER_HOME}/server/discosrv \
    -listen=":${SERV_PORT}" \
    -db-dir="${USER_HOME}/db/discosrv.db" \
    ${DISCO_OPTS}
```

Additional modifications of course would be needed on the reverse proxy and I believe if using nginx as a reverse proxy these would be:

```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Client-Port $remote_port;
proxy_set_header X-SSL-Cert $ssl_client_cert;
ssl_verify_client optional_no_ca;
```

**Comment by t4skforce** [comment]
from docker perspective yes, I also  had a quick look into the parameters supported in discosrv https://github.com/syncthing/syncthing/blob/main/cmd/stdiscosrv/main.go seems to be okay. keep me posted if it works and how, then we can update the readme so reverse proxy setup is documented.

**Comment by kevdogg** [comment]
I basically used your dockerfile and changed it a bit:

ENV DISCO_OPTS      "-http"

CMD ${USER_HOME}/server/discosrv \
    -listen=":${SERV_PORT}" \
    -db-dir="${USER_HOME}/db/discosrv.db" \
    ${DISCO_OPTS}

Supposedly the generated certs are used for discovery and replication.

My only problem right now is the lack of logging facilities.  The container was working but now I'm getting a 404 (not found) when I try curling or wget http://<container ip>:8443

Is that normal?
